name: Release Helm chart
on:
  push:
    branches:
      - master
    paths:
      - 'charts/postfix-exporter/Chart.yaml'
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/helm-release.yml@57366a300d9a0523621af11c2efcde2fdcf16aa3 # v1.0.41
    secrets: inherit
    with:
      upload_as_oci: true
      chart_name: postfix-exporter
